#!/bin/bash

function startOrRestart() {
  startOrRestartImpl "$1" &
}

function startOrRestartImpl() {
  EXECUTABLE="$(echo $1 | cut -f 1 -d " ")"
  pkill $EXECUTABLE && pwait $EXECUTABLE; $1
}

startOrRestart sxhkd

bspc monitor -d {1..10} {a..j}

~/.setup_monitors.sh

bspc config border_width         5
bspc config window_gap          10
bspc config top_padding 9

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#182032"
bspc config focused_border_color "#44475a"

bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr &

startOrRestart polybar
startOrRestart dunst
startOrRestart picom -b
~/.fehbg

xss-lock --transfer-sleep-lock -- "lock.sh" --no-fork
