#!/bin/bash

function battery() {
	bat=`ls /sys/class/power_supply | grep BAT | head -n 1`
	cat /sys/class/power_supply/${bat}/capacity
}

function battery_stat() {
	bat=`ls /sys/class/power_supply | grep BAT | head -n 1`
	cat /sys/class/power_supply/${bat}/status
}

if [[ "$1" == "--bat" ]]; then
	battery
elif [[ "$1" == "--bat-st" ]]; then
	battery_stat
fi

