[zsh.files]
profiles = "~/.profiles/"
"zsh/zshrc" = "~/.zshrc"

[zsh.variables]
theme = "robbyrussell"
plugins = "git docker docker-compose aliases copybuffer copyfile command-not-found history"
# add extra plugins here, for example local ones
plugins_extra = ""
# display '/home/user' instead of '~'
prompt_replacement = "${PROMPT/\\%c/\\%d}"
editor = "nano"
# the zshrc will automatically set JAVA_HOME and add the JDK to the path
java_dir = "~/.jdks"

[i3.files]
i3 = "~/.config/i3"

[i3]
depends = [ "bin" ]

[i3.variables]
file_manager = "nautilus"
terminal = "kitty"
# this will get added to the launch command (super + t)
# use this to prevent picom from matching flags as the wm class name
# this default value will open kitty in the directory that the current focused windows is in
terminal_arguments = "`xcwd`"
# will restart i3 once changes are detected IN THE GLOBAL CONTEXT
# (will also restart if, say, the ZSH config changed)
# only runs when the 'i3' package is enabled in the 'local.toml' file
auto_restart_i3 = "false"

[neofetch.files]
neofetch = "~/.config/neofetch"

[nvim.files]
nvim = "~/.config/nvim"

[kitty.files]
kitty = "~/.config/kitty"

[polybar.files]
polybar = "~/.config/polybar"

[polybar.variables]
# get the right id by using 'xinput test-xi2 --root | grep \(KeyPress\) -A 1', typing something, and then reading the 'device' field
keyboard_id = "AT Translated Set 2 keyboard"
# get the right id by using 'ls -1 /sys/class/power_supply/'
battery_id = "BAT1"

[dunst.files]
dunst = "~/.config/dunst"

[bin.files]
bin = "~/bin"

[picom.files]
picom = "~/.config/picom"

[helpers]
bool = ".dotter/helpers/bool.rhai"
