[global.variables]
terminal = "kitty"
task_manager = "btop"
file_manager = "ranger"

[zsh.files]
profiles = "~/.profiles/"
"zsh/zshrc" = "~/.config/zsh/.zshrc"

[zsh.variables]
plugins = "common-aliases git docker docker-compose aliases copybuffer copyfile command-not-found history"
# add extra plugins here, for example local ones
plugins_extra = ""
plugins_external = "zsh-users/zsh-syntax-highlighting zsh-users/zsh-autosuggestions"
editor = "nvim"
# the zshrc will automatically set JAVA_HOME and add the JDK to the path
java_dir = "~/.jdks"

[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"

[wm]
depends = [ "global" ]

[wm.variables]
# this default value will open the terminal in the directory that the current focused windows is in
terminal_arguments = "\"`xcwd`\""

[i3.files]
i3 = "~/.config/i3"

[i3]
depends = [ "bin", "wm" ]

[i3.variables]
file_manager = "nautilus"

[bspwm]
depends = [ "bin", "sxhkd", "wm" ]

[bspwm.files]
bspwm = "~/.config/bspwm"

[sxhkd.files]
"sxhkd/sxhkdrc" = "~/.config/sxhkd/sxhkdrc"

[hyprland]
depends = [ "wm" ]

[hyprland.files]
hyprland = "~/.config/hypr"

[neofetch.files]
neofetch = "~/.config/neofetch"

[nvim.files]
nvim = "~/.config/nvim"

[kitty.files]
kitty = "~/.config/kitty"

[polybar.files]
polybar = "~/.config/polybar"

[polybar.variables]
# get the id by running:
# xinput test-xi2 --root | grep \(KeyPress\) -A 1
# then type something in and read the 'device' field
keyboard_id = "AT Translated Set 2 keyboard"
# ls -1 /sys/class/power_supply/
battery_id = "BAT1"
# for i in /sys/class/thermal/thermal_zone*; do echo "$i: $(<$i/type)"; done
thermal_zone = "2"

[eww]
depends = [ "global" ]

[eww.files]
eww = "~/.config/eww"
"eww/scripts/music_info" = { target = "~/.config/eww/scripts/music_info", type = "symbolic" }

[waybar]
depends = [ "global" ]

[waybar.files]
waybar = "~/.config/waybar"

[dunst.files]
dunst = "~/.config/dunst"

[bin.files]
bin = "~/.local/bin"

[picom.files]
picom = "~/.config/picom"

[rofi.files]
rofi = "~/.config/rofi"

[btop.files]
btop = "~/.config/btop"

[ranger.files]
ranger = "~/.config/ranger"

[git.files]
"git/config" = "~/.config/git/config.global"
"git/template" = "~/.config/git/template"

[helpers]
bool = ".dotter/helpers/bool.rhai"
