export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="{{theme}}"
HYPHEN_INSENSITIVE="true"

zstyle ':omz:update' mode reminder  # just remind me to update when it's time
zstyle ':omz:update' frequency 7

DISABLE_MAGIC_FUNCTIONS="true"
COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="dd.mm.yyyy"

plugins=({{plugins}})

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#808080,italic"

source $ZSH/oh-my-zsh.sh

export LANG=en_GB.UTF-8

EDITOR="{{editor}}"
alias zshconfig="$EDITOR {{dotter.current_dir}}/zsh/zshrc"
alias ohmyzsh="$EDITOR {{dotter.current_dir}}/zsh/oh-my-zsh"
alias dotfiles="cd {{dotter.current_dir}}"
# make avaliable to all sessions as an environment variable
DOTFILES_FOLDER="{{dotter.current_dir}}"

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

for FILE in ~/.profiles*/* ; do source $FILE ; done

if [ "{{prompt_replacement}}" != "" ]
then
  PROMPT={{prompt_replacement}}
fi

{{#if java_dir}}
if [ "{{java_dir}}" != "" ] && [ -h "{{java_dir}}" ]
then
  # get latest JDK in java_dir
  export JAVA_HOME={{java_dir}}/$(ls {{java_dir}} | sed '/-/!{s/$/_/}' | sort -V | sed 's/_$//' | tail -1)
  # add the bin dir of the found java home to the path
  if [ -z $JAVA_HOME ]; then
    echo JAJA: $JAVA_HOME
    PATH=$PATH:$JAVA_HOME/bin
  fi
fi
{{/if}}

# don't save commands starting with a space to the history file
setopt HIST_IGNORE_SPACE

# human readable format - very handy
alias lh="ls -h"

# load plugins that are located like this: '~/.zsh-plugins/my-plugin/my-plugin.zsh'
# KEEP AT END (zsh-syntax-highlighting requires this)
for f in ~/.zsh-plugins/*; do
  file="$f/"$(echo $f | rev | cut -f 1 -d / | rev)".zsh"
  if [ -f $file ]; then
    source $file
  fi
done
