export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="{{theme}}"
HYPHEN_INSENSITIVE="true"

zstyle ':omz:update' mode reminder  # just remind me to update when it's time
zstyle ':omz:update' frequency 7

DISABLE_MAGIC_FUNCTIONS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="dd.mm.yyyy"

plugins=({{plugins}} {{plugins_extra}})

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#808080,italic"

source ~/.profile

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8

export EDITOR="{{editor}}"
alias zshconfig="$EDITOR {{dotter.current_dir}}/zsh/zshrc"
alias ohmyzsh="$EDITOR {{dotter.current_dir}}/zsh/oh-my-zsh"
# make avaliable to all sessions as an environment variable
export DOTFILES_FOLDER="{{dotter.current_dir}}"

function dotfiles() {
  if [ "$1" != "" ]; then
    INPUT=$(echo "$1" | tr '[:upper:]' '[:lower:]')
    if [ "$INPUT" = "github" ] || [ "$INPUT" = "repo" ]; then
      # run in subshell to prevent current shell from cd'ing into the dotfiles repo
      # do in subshell to prevent CDing in current session
      (
        cd {{dotter.current_dir}} \
        && export REPO="$(git config --get remote.origin.url)" \
        && [[ ! "$REPO" =~ "^http" ]] && REPO="$(echo $REPO | sed 's/:/\//' | sed 's/git@/https:\/\//g')" || : \
        && [ "$REPO" != "" ] \
          && ((xdg-open "$REPO" &) && echo "Opened '$REPO' in your Browser.") \
          || echo "No git repo found."
      )
      return 0
    elif [ -d "{{dotter.current_dir}}/$1" ]; then
      cd {{dotter.current_dir}}/$1
      pwd
    else
      echo Directory \'$1\' not found.
      return 1
    fi
  else
    cd {{dotter.current_dir}}
  fi
  # show all files, except for "." and ".." (current / upper directory)
  ls -a -I "." -I ".."
}

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

for FILE in ~/.profiles*/* ; do source $FILE ; done

if [ "{{prompt_replacement}}" != "" ]
then
  PROMPT={{prompt_replacement}}
fi

{{#if java_dir}}
if [ -d $(echo {{java_dir}}) ]
then
  # get latest JDK in java_dir
  export JAVA_HOME={{java_dir}}/$(ls {{java_dir}} | sed '/-/!{s/$/_/}' | sort -V | sed 's/_$//' | tail -2)
  # add the bin dir of the found java home to the path
  if [ ! -z $JAVA_HOME ]; then
    PATH=$PATH:$JAVA_HOME/bin
  fi
fi
{{/if}}

# don't save commands starting with a space to the history file
setopt HIST_IGNORE_SPACE

# human readable format - very handy
alias lh="ls -h"

# like 'gss' (git status short), but with the branch name included
alias gsb="git status -sb"

# delete whole word with ctrl + backspace
bindkey ^H backward-delete-word

# load plugins that are located like this: '~/.zsh-plugins/my-plugin/my-plugin.zsh'
# KEEP AT END (zsh-syntax-highlighting requires this)
if [ -d ~/.zsh-plugins ]; then
  for f in ~/.zsh-plugins/*; do
    file="$f/"$(echo $f | rev | cut -f 1 -d / | rev)".zsh"
    if [ -f $file ]; then
      source $file
    fi
  done
fi

compctl -/ -W ~/dotfiles dotfiles
