HYPHEN_INSENSITIVE="true"
DISABLE_MAGIC_FUNCTIONS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export EDITOR="{{editor}}"
alias zshconfig="$EDITOR {{dotter.current_dir}}/zsh/zshrc"

# dont save commands starting with a space to the history file
setopt HIST_IGNORE_SPACE
HIST_STAMPS="dd.mm.yyyy"
HISTSIZE=1000
SAVEHIST=50000
HISTFILE=${XDG_STATE_HOME:-$HOME/.local/state}/.zsh_history

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#808080"

source ~/.profile

# make avaliable to all sessions as an environment variable
export DOTFILES_FOLDER="{{dotter.current_dir}}"

for FILE in ~/.profiles*/* ; do source $FILE ; done

{{#if java_dir}}
if [ -d $(echo {{java_dir}}) ]; then
  # get latest JDK in java_dir
  export JAVA_HOME={{java_dir}}/$(ls {{java_dir}} | sed '/-/!{s/$/_/}' | sort -V | sed 's/_$//' | tail -2)
  # add the bin dir of the found java home to the path
  [ ! -z $JAVA_HOME ] && PATH="$PATH:$JAVA_HOME/bin" || true
fi
{{/if}}

bindkey -a '^ ' edit-command-line

compctl -/ -W ~/dotfiles dotfiles

source ~/.local/share/zinit/zinit.git/zinit.zsh
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

plugins=({{plugins}} {{plugins_extra}})
while read LINE; do
  zinit snippet OMZ::plugins/$LINE/$LINE.plugin.zsh;
done <<< $(echo $plugins | tr ' ' '\n')
zinit snippet OMZ::lib/history.zsh
zinit snippet OMZ::lib/completion.zsh
zinit snippet OMZ::lib/key-bindings.zsh

# delete whole word with ctrl + backspace
bindkey ^H backward-delete-word

zinit ice blockf atpull'zinit creinstall -q .'
while read LINE; do
  zinit light $LINE;
done <<< $(echo "{{plugins_external}}" | tr ' ' '\n')

command -v starship &>/dev/null && eval "$(starship init zsh)" || true

# start vim mode
bindkey -v
